### ISSUE TITLE
1.0.2-c03be31 No Google Drive Option

### ISSUE THREAD

**Issue by chrismez** [GedasFX/decky-cloud-save#3]
Installing 1.0.2-c03be31only lists OneDrive and Dropbox as cloud storage provider targets, however documentation refers to Google Drive?

**Comment by GedasFX** [comment]
Hey,

Unfortunately, for Google Drive you need to use the advanced flow. The default browser used by Steam is not trusted by Google, and will not allow you to sign in. It used to be an option there, but now is removed until Valve updates their browser.

If needed I can make some utility scripts to set things up in desktop mode - still one click solutions instead of CLI. Would do it for google explicitly here. Would that be helpful?

**Comment by chrismez** [comment]
That would be awesome, I mean I'm sure I could fumble through it, I'm not against trying to set it up via commandline for myself, but you're bound to help a much wider audience if you can put a script together. I'm also happy helping to test it out if you decide you want to do so,

**Comment by GedasFX** [comment]
PR made for v1.1.1
