### ISSUE TITLE
Plugin buttons in Steam no longer do anything

### ISSUE THREAD

**Issue by mdeguzis** [GedasFX/decky-cloud-save#56]
I had to downgrade to the prior version or else the buttons for configure/add path do nothing when pressed. I tried both the stable/pre-release Decky Loader release. I don't think anything gets generated when tailing journalctl.

Working on old version:
```
[decky-cloud-save]$ grep version package.json 
  "version": "1.3.1-1",
```

I typically use Steam beta release.

**Comment by GedasFX** [comment]
Rechecked on version 1.3.3, yeah the issue seems to be only on Steam beta. Okay on Stable.
It appears that the decky framework itself is broken right now, so likely more plugins are not working. As to why earlier version works, so far its unclear. I would avoid using the beta release for now at least.

**Comment by mdeguzis** [comment]
Sure. I always wondered how plugin authors "resync" with Steam to fix these kinds of issues.

**Comment by GedasFX** [comment]
Fix released. https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/529
