### ISSUE TITLE
Sync on start triggered on a Steam Cloud game

### ISSUE THREAD

**Issue by AkazaRenn** [GedasFX/decky-cloud-save#97]
Tested with the free demo of this game https://store.steampowered.com/app/2401970/Ace_Attorney_Investigations_Collection/

This demo supports Steam Cloud, but still triggers the sync.

**Comment by AkazaRenn** [comment]
Launching loop seems caused by the game itself or something else

**Comment by GedasFX** [comment]
Relates to #81

**Comment by GedasFX** [comment]
I will try debugging this today, time to get to the bottom of this :D

**Comment by GedasFX** [comment]
Identified issue caused by the fact that demos have a app_type = 8, Also found out that type=tool has app_type of 4 (to not lose research).

Ultimately I found a better solution, will check if store page has category 23 (Steam Cloud). If no store page - nonsteam game, if steam game but no category - still no cloud. The demo you tried DOES NOT support steam cloud.

The game: https://steamdb.info/app/2401970/
The demo: https://steamdb.info/app/2728410/

**Comment by GedasFX** [comment]
![image](https://github.com/user-attachments/assets/b3ef617a-b1da-47da-8bbc-0c4265070cb4)
Aaand instantly realized my mistake, yes sorry, the demo does support steam clouds, I was testing with Aperture Desk Job (1902490), which does not have cloud, and got the ids mixed up.

![image](https://github.com/user-attachments/assets/cc35f21f-063c-47be-ace4-7f10142b8f1e)

**Comment by AkazaRenn** [comment]
Interesting, then it's a Steam bug showing the cloud icon on it

**Comment by GedasFX** [comment]
Tested with various ids I had installed, thats how I found out about all the various types. For now will just stick with category, and see if it works out.

**Comment by GedasFX** [comment]
Also, found out about even more cool tools:
https://store.steampowered.com/account/remotestorageapp/?appid=2728410
https://store.steampowered.com/account/remotestorageapp
